Implemented Upcoming Leaves of team in home screen
joshsoftware/intranet-mobile pull request #66
Opened 2023-06-07 09:43 UTC by tanmaythole

### Ticket Links:
https://trello.com/c/NhHYXQ2t/56-show-upcoming-leaves-of-team-members-on-dashboard

---

### Pull Request Description:
Implemented upcoming leaves of team members in home screen

---

### Pull Request Submission Checklist:
- [X] Self-reviewed the code prior to submitting PR
- [X] Done a thorough testing on local
- [X] Make sure no eslint and typescript issues.
- [X] Update Trello ticket and sub-tasks status
---

### Screenshots/Videos:

2023-06-07 10:29 UTC, Chetan-Satpute-Josh commented on src/app/screens/HomeScreen/index.tsx
>    text: {
I think we should remove this.

2023-06-07 10:35 UTC, Chetan-Satpute-Josh requested changes

2023-06-07 10:35 UTC, Chetan-Satpute-Josh commented on src/app/screens/HomeScreen/index.tsx
>    text: {
I think we should remove this

2023-06-07 10:38 UTC, tanmaythole commented on src/app/screens/HomeScreen/index.tsx
>    text: {
👍🏻

2023-06-07 10:40 UTC, Chetan-Satpute-Josh approved these changes

2023-06-13 22:48 UTC, Chetan-Satpute-Josh approved these changes

2023-06-14 02:29 UTC, merged